/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderAvroCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7842309254653807150L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderAvroCreatedEvent\",\"namespace\":\"com.example.events\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"orderId\",\"type\":\"long\"},{\"name\":\"productId\",\"type\":\"long\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"clientLat\",\"type\":\"double\"},{\"name\":\"clientLon\",\"type\":\"double\"},{\"name\":\"occurredAt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderAvroCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderAvroCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderAvroCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderAvroCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderAvroCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderAvroCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderAvroCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderAvroCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderAvroCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventId;
  private long orderId;
  private long productId;
  private int quantity;
  private double clientLat;
  private double clientLon;
  private java.lang.CharSequence occurredAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderAvroCreatedEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param orderId The new value for orderId
   * @param productId The new value for productId
   * @param quantity The new value for quantity
   * @param clientLat The new value for clientLat
   * @param clientLon The new value for clientLon
   * @param occurredAt The new value for occurredAt
   */
  public OrderAvroCreatedEvent(java.lang.CharSequence eventId, java.lang.Long orderId, java.lang.Long productId, java.lang.Integer quantity, java.lang.Double clientLat, java.lang.Double clientLon, java.lang.CharSequence occurredAt) {
    this.eventId = eventId;
    this.orderId = orderId;
    this.productId = productId;
    this.quantity = quantity;
    this.clientLat = clientLat;
    this.clientLon = clientLon;
    this.occurredAt = occurredAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return orderId;
    case 2: return productId;
    case 3: return quantity;
    case 4: return clientLat;
    case 5: return clientLon;
    case 6: return occurredAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: orderId = (java.lang.Long)value$; break;
    case 2: productId = (java.lang.Long)value$; break;
    case 3: quantity = (java.lang.Integer)value$; break;
    case 4: clientLat = (java.lang.Double)value$; break;
    case 5: clientLon = (java.lang.Double)value$; break;
    case 6: occurredAt = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public long getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(long value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public long getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(long value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'clientLat' field.
   * @return The value of the 'clientLat' field.
   */
  public double getClientLat() {
    return clientLat;
  }


  /**
   * Sets the value of the 'clientLat' field.
   * @param value the value to set.
   */
  public void setClientLat(double value) {
    this.clientLat = value;
  }

  /**
   * Gets the value of the 'clientLon' field.
   * @return The value of the 'clientLon' field.
   */
  public double getClientLon() {
    return clientLon;
  }


  /**
   * Sets the value of the 'clientLon' field.
   * @param value the value to set.
   */
  public void setClientLon(double value) {
    this.clientLon = value;
  }

  /**
   * Gets the value of the 'occurredAt' field.
   * @return The value of the 'occurredAt' field.
   */
  public java.lang.CharSequence getOccurredAt() {
    return occurredAt;
  }


  /**
   * Sets the value of the 'occurredAt' field.
   * @param value the value to set.
   */
  public void setOccurredAt(java.lang.CharSequence value) {
    this.occurredAt = value;
  }

  /**
   * Creates a new OrderAvroCreatedEvent RecordBuilder.
   * @return A new OrderAvroCreatedEvent RecordBuilder
   */
  public static com.example.events.OrderAvroCreatedEvent.Builder newBuilder() {
    return new com.example.events.OrderAvroCreatedEvent.Builder();
  }

  /**
   * Creates a new OrderAvroCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderAvroCreatedEvent RecordBuilder
   */
  public static com.example.events.OrderAvroCreatedEvent.Builder newBuilder(com.example.events.OrderAvroCreatedEvent.Builder other) {
    if (other == null) {
      return new com.example.events.OrderAvroCreatedEvent.Builder();
    } else {
      return new com.example.events.OrderAvroCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new OrderAvroCreatedEvent RecordBuilder by copying an existing OrderAvroCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderAvroCreatedEvent RecordBuilder
   */
  public static com.example.events.OrderAvroCreatedEvent.Builder newBuilder(com.example.events.OrderAvroCreatedEvent other) {
    if (other == null) {
      return new com.example.events.OrderAvroCreatedEvent.Builder();
    } else {
      return new com.example.events.OrderAvroCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderAvroCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderAvroCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<OrderAvroCreatedEvent> {

    private java.lang.CharSequence eventId;
    private long orderId;
    private long productId;
    private int quantity;
    private double clientLat;
    private double clientLon;
    private java.lang.CharSequence occurredAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.events.OrderAvroCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productId)) {
        this.productId = data().deepCopy(fields()[2].schema(), other.productId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.clientLat)) {
        this.clientLat = data().deepCopy(fields()[4].schema(), other.clientLat);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.clientLon)) {
        this.clientLon = data().deepCopy(fields()[5].schema(), other.clientLon);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[6].schema(), other.occurredAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderAvroCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.events.OrderAvroCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productId)) {
        this.productId = data().deepCopy(fields()[2].schema(), other.productId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.clientLat)) {
        this.clientLat = data().deepCopy(fields()[4].schema(), other.clientLat);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.clientLon)) {
        this.clientLon = data().deepCopy(fields()[5].schema(), other.clientLon);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[6].schema(), other.occurredAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public long getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder setOrderId(long value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder clearOrderId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public long getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder setProductId(long value) {
      validate(fields()[2], value);
      this.productId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder clearProductId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder setQuantity(int value) {
      validate(fields()[3], value);
      this.quantity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder clearQuantity() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'clientLat' field.
      * @return The value.
      */
    public double getClientLat() {
      return clientLat;
    }


    /**
      * Sets the value of the 'clientLat' field.
      * @param value The value of 'clientLat'.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder setClientLat(double value) {
      validate(fields()[4], value);
      this.clientLat = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'clientLat' field has been set.
      * @return True if the 'clientLat' field has been set, false otherwise.
      */
    public boolean hasClientLat() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'clientLat' field.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder clearClientLat() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'clientLon' field.
      * @return The value.
      */
    public double getClientLon() {
      return clientLon;
    }


    /**
      * Sets the value of the 'clientLon' field.
      * @param value The value of 'clientLon'.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder setClientLon(double value) {
      validate(fields()[5], value);
      this.clientLon = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'clientLon' field has been set.
      * @return True if the 'clientLon' field has been set, false otherwise.
      */
    public boolean hasClientLon() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'clientLon' field.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder clearClientLon() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurredAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getOccurredAt() {
      return occurredAt;
    }


    /**
      * Sets the value of the 'occurredAt' field.
      * @param value The value of 'occurredAt'.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder setOccurredAt(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.occurredAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'occurredAt' field has been set.
      * @return True if the 'occurredAt' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'occurredAt' field.
      * @return This builder.
      */
    public com.example.events.OrderAvroCreatedEvent.Builder clearOccurredAt() {
      occurredAt = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderAvroCreatedEvent build() {
      try {
        OrderAvroCreatedEvent record = new OrderAvroCreatedEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.lang.Long) defaultValue(fields()[1]);
        record.productId = fieldSetFlags()[2] ? this.productId : (java.lang.Long) defaultValue(fields()[2]);
        record.quantity = fieldSetFlags()[3] ? this.quantity : (java.lang.Integer) defaultValue(fields()[3]);
        record.clientLat = fieldSetFlags()[4] ? this.clientLat : (java.lang.Double) defaultValue(fields()[4]);
        record.clientLon = fieldSetFlags()[5] ? this.clientLon : (java.lang.Double) defaultValue(fields()[5]);
        record.occurredAt = fieldSetFlags()[6] ? this.occurredAt : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderAvroCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderAvroCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderAvroCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderAvroCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.orderId);

    out.writeLong(this.productId);

    out.writeInt(this.quantity);

    out.writeDouble(this.clientLat);

    out.writeDouble(this.clientLon);

    out.writeString(this.occurredAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.orderId = in.readLong();

      this.productId = in.readLong();

      this.quantity = in.readInt();

      this.clientLat = in.readDouble();

      this.clientLon = in.readDouble();

      this.occurredAt = in.readString(this.occurredAt instanceof Utf8 ? (Utf8)this.occurredAt : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.orderId = in.readLong();
          break;

        case 2:
          this.productId = in.readLong();
          break;

        case 3:
          this.quantity = in.readInt();
          break;

        case 4:
          this.clientLat = in.readDouble();
          break;

        case 5:
          this.clientLon = in.readDouble();
          break;

        case 6:
          this.occurredAt = in.readString(this.occurredAt instanceof Utf8 ? (Utf8)this.occurredAt : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










