/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockAvroFailedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6149378740664997598L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockAvroFailedEvent\",\"namespace\":\"com.example.events\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"orderId\",\"type\":\"long\"},{\"name\":\"reason\",\"type\":\"string\"},{\"name\":\"instant\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockAvroFailedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockAvroFailedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockAvroFailedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockAvroFailedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockAvroFailedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockAvroFailedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockAvroFailedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockAvroFailedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockAvroFailedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventId;
  private long orderId;
  private java.lang.CharSequence reason;
  private java.lang.CharSequence instant;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockAvroFailedEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param orderId The new value for orderId
   * @param reason The new value for reason
   * @param instant The new value for instant
   */
  public StockAvroFailedEvent(java.lang.CharSequence eventId, java.lang.Long orderId, java.lang.CharSequence reason, java.lang.CharSequence instant) {
    this.eventId = eventId;
    this.orderId = orderId;
    this.reason = reason;
    this.instant = instant;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return orderId;
    case 2: return reason;
    case 3: return instant;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: orderId = (java.lang.Long)value$; break;
    case 2: reason = (java.lang.CharSequence)value$; break;
    case 3: instant = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public long getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(long value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The value of the 'reason' field.
   */
  public java.lang.CharSequence getReason() {
    return reason;
  }


  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.CharSequence value) {
    this.reason = value;
  }

  /**
   * Gets the value of the 'instant' field.
   * @return The value of the 'instant' field.
   */
  public java.lang.CharSequence getInstant() {
    return instant;
  }


  /**
   * Sets the value of the 'instant' field.
   * @param value the value to set.
   */
  public void setInstant(java.lang.CharSequence value) {
    this.instant = value;
  }

  /**
   * Creates a new StockAvroFailedEvent RecordBuilder.
   * @return A new StockAvroFailedEvent RecordBuilder
   */
  public static com.example.events.StockAvroFailedEvent.Builder newBuilder() {
    return new com.example.events.StockAvroFailedEvent.Builder();
  }

  /**
   * Creates a new StockAvroFailedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockAvroFailedEvent RecordBuilder
   */
  public static com.example.events.StockAvroFailedEvent.Builder newBuilder(com.example.events.StockAvroFailedEvent.Builder other) {
    if (other == null) {
      return new com.example.events.StockAvroFailedEvent.Builder();
    } else {
      return new com.example.events.StockAvroFailedEvent.Builder(other);
    }
  }

  /**
   * Creates a new StockAvroFailedEvent RecordBuilder by copying an existing StockAvroFailedEvent instance.
   * @param other The existing instance to copy.
   * @return A new StockAvroFailedEvent RecordBuilder
   */
  public static com.example.events.StockAvroFailedEvent.Builder newBuilder(com.example.events.StockAvroFailedEvent other) {
    if (other == null) {
      return new com.example.events.StockAvroFailedEvent.Builder();
    } else {
      return new com.example.events.StockAvroFailedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockAvroFailedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockAvroFailedEvent>
    implements org.apache.avro.data.RecordBuilder<StockAvroFailedEvent> {

    private java.lang.CharSequence eventId;
    private long orderId;
    private java.lang.CharSequence reason;
    private java.lang.CharSequence instant;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.events.StockAvroFailedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.instant)) {
        this.instant = data().deepCopy(fields()[3].schema(), other.instant);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing StockAvroFailedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.events.StockAvroFailedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.instant)) {
        this.instant = data().deepCopy(fields()[3].schema(), other.instant);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public long getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder setOrderId(long value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder clearOrderId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * @return The value.
      */
    public java.lang.CharSequence getReason() {
      return reason;
    }


    /**
      * Sets the value of the 'reason' field.
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder setReason(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.reason = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'reason' field.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder clearReason() {
      reason = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'instant' field.
      * @return The value.
      */
    public java.lang.CharSequence getInstant() {
      return instant;
    }


    /**
      * Sets the value of the 'instant' field.
      * @param value The value of 'instant'.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder setInstant(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.instant = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'instant' field has been set.
      * @return True if the 'instant' field has been set, false otherwise.
      */
    public boolean hasInstant() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'instant' field.
      * @return This builder.
      */
    public com.example.events.StockAvroFailedEvent.Builder clearInstant() {
      instant = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockAvroFailedEvent build() {
      try {
        StockAvroFailedEvent record = new StockAvroFailedEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.lang.Long) defaultValue(fields()[1]);
        record.reason = fieldSetFlags()[2] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.instant = fieldSetFlags()[3] ? this.instant : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockAvroFailedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockAvroFailedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockAvroFailedEvent>
    READER$ = (org.apache.avro.io.DatumReader<StockAvroFailedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.orderId);

    out.writeString(this.reason);

    out.writeString(this.instant);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.orderId = in.readLong();

      this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);

      this.instant = in.readString(this.instant instanceof Utf8 ? (Utf8)this.instant : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.orderId = in.readLong();
          break;

        case 2:
          this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);
          break;

        case 3:
          this.instant = in.readString(this.instant instanceof Utf8 ? (Utf8)this.instant : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










